### ISSUE TITLE
pymongo connection failure - scan results don't update

### ISSUE THREAD

**Issue by thofli** [jfalken/github_commit_crawler#8]
Keep getting this error in the ghcc proc logs (see screenshot)

`Error: (<class 'pymongo.errors.ConnectionFailure'>, ConnectionFailure('[Errno 111] Connection refused',), <traceback object at 0x2cdc5f0>)`

![screen shot 2015-11-06 at 12 50 00 pm](https://cloud.githubusercontent.com/assets/10637237/11007777/d9c8d03a-8491-11e5-9e9f-3be8ee62cac3.png)

Everything installs fine and I'm able to successfully run one scan.  Then subsequent scans run (verified through Crawler Logs), but the scan data does not populate via the ui.  I've been able to reproduce this error several times.  Thanks.

**Comment by jfalken** [comment]
Are you running this inside the docker container? If so, under the process supervisor screen, is MongoDB listed as up and running? you can try to restart the process

**Comment by thofli** [comment]
Yes, I'm running it inside the docker container.  MongoDB is listed as running too.  I've tried restarting the process, but it does not fix the issue.  When I run subsequent scans they run successfully and through the Crawler Logs I can see audit findings that correspond with the most recent scan time.  However, the new scan results never update via the ui.

**Comment by jfalken** [comment]
Its possible there are no new entries after subsequent scans. A few things to note here: The log file does not clear; so you may be seeing old error messages. Additionally, the scanner picks up where it left off - so it will not alert twice on previous findings; if there have not been any new commits since the last scan, there will be nothing else to report.

**Comment by thofli** [comment]
Okay ... good to know.  My assumption was the scans ran from the beginning each time so new keywords would be found.  I'll hold off on scanning for a few days and then see how it goes. Thanks for the info (and support).  Great work on ghcc ... awesome tool.

**Comment by jfalken** [comment]
thanks, glad to be of help :)    closing issue now.
